[[constraint]]
  name = "github.com/go-chi/chi"
  version = "v3.3.1"
[[constraint]]
  name = "github.com/go-chi/cors"
  version = "v1.0.0"
[[constraint]]
  name = "github.com/go-chi/render"
  version = "v1.0.0"
[[constraint]]
  name = "github.com/jmoiron/sqlx"